<?php

namespace ContainerLcCc2fx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M6c_RvXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.M6c.RvX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M6c.RvX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamer' => ['privates', '.errored..service_locator.M6c.RvX.App\\Entity\\Reclamer', NULL, 'Cannot autowire service ".service_locator.M6c.RvX": it references class "App\\Entity\\Reclamer" but no such service exists.'],
        ], [
            'reclamer' => 'App\\Entity\\Reclamer',
        ]);
    }
}
