<?php

namespace ContainerLcCc2fx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamerTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ReclamerType' shared autowired service.
     *
     * @return \App\Form\ReclamerType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ReclamerType'] = new \App\Form\ReclamerType();
    }
}
