<?php

namespace ContainerLcCc2fx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamerRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ReclamerRepository' shared autowired service.
     *
     * @return \App\Repository\ReclamerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ReclamerRepository'] = new \App\Repository\ReclamerRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
