<?php

namespace ContainerLcCc2fx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamerService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.M6c.RvX.App\Entity\Reclamer' shared service.
     *
     * @return \App\Entity\Reclamer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.M6c.RvX": it references class "App\\Entity\\Reclamer" but no such service exists.');
    }
}
