<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLcCc2fx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLcCc2fx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLcCc2fx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLcCc2fx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLcCc2fx\App_KernelProdContainer([
    'container.build_hash' => 'LcCc2fx',
    'container.build_id' => 'f3146a50',
    'container.build_time' => 1612954960,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLcCc2fx');
