<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'reclamer_index' => [[], ['_controller' => 'App\\Controller\\ReclamerController::index'], [], [['text', '/reclamer/']], [], []],
    'reclamer_index_etudiant' => [[], ['_controller' => 'App\\Controller\\ReclamerController::indexEtudiant'], [], [['text', '/reclamer/etudiant']], [], []],
    'reclamer_new' => [[], ['_controller' => 'App\\Controller\\ReclamerController::new'], [], [['text', '/reclamer/new']], [], []],
    'reclamer_show' => [['id'], ['_controller' => 'App\\Controller\\ReclamerController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reclamer']], [], []],
    'reclamer_edit' => [['id'], ['_controller' => 'App\\Controller\\ReclamerController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/reclamer']], [], []],
    'reclamer_delete' => [['id'], ['_controller' => 'App\\Controller\\ReclamerController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reclamer']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
