<?php

namespace ContainerMOPKM7B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ReclamerType' shared autowired service.
     *
     * @return \App\Form\ReclamerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ReclamerType.php';

        return $container->privates['App\\Form\\ReclamerType'] = new \App\Form\ReclamerType();
    }
}
