<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMOPKM7B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMOPKM7B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMOPKM7B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMOPKM7B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMOPKM7B\App_KernelDevDebugContainer([
    'container.build_hash' => 'MOPKM7B',
    'container.build_id' => '5ed9b227',
    'container.build_time' => 1612952628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMOPKM7B');
